version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    network_mode: 'host'
    ports:
      - '5672:5672'
      - '15672:15672'
  jee-server:
    build: .
    ports:
    - "8080:8080"
