version: '3'

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    network_mode: 'host'
    ports:
      - '5672:5672'
      - '15672:15672'
  jee-server:
    build: .
    ports:
    - "8080:8080"
    environment:
      AUTHENTIFICATION_DATABASE: ${TCD_DB_AUTHENTICATION_DATABASE}
      DB_USERNAME: ${TCD_DB_USERNAME}
      DB_PASSWORD: ${TCD_DB_PASSWORD}
      DB_NAME: ${TCD_DB_NAME}
      DB_PORT: ${TCD_DB_PORT}
      DB_HOST: ${TCD_DB_HOST}
