version: '3'

services:
  mongo:
    image: mongo
    container_name: 'tcd-mongo'
    restart: always
    volumes:
      - "${TCD_MONGO_DATA_PATH:-./mongoData}:/data/db"
    ports:
      - "${TCD_MONGO_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${TCD_MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${TCD_MONGO_ROOT_PASSWORD:-admin}

  mongo-express:
    image: mongo-express
    container_name: 'tcd-mongo-express'
    restart: always
    ports:
      - "${TCD_MONGO_EXPRESS_PORT:-9001}:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${TCD_MONGO_EXPRESS_ADMIN_USERNAME:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${TCD_MONGO_EXPRESS_ADMIN_PASSWORD:-admin}
      - ME_CONFIG_BASICAUTH_USERNAME=${TCD_MONGO_EXPRESS_USER_USERNAME:-user}
      - ME_CONFIG_BASICAUTH_PASSWORD=${TCD_MONGO_EXPRESS_USER_PASSWORD:-user}

  rabbitmq:
    hostname: 'tcdrabbit'
    image: 'rabbitmq:3.6-management-alpine'
    container_name: 'tcd-rabbitmq'
    restart: always
    ports:
      - "${TCD_RABBITMQ_MANAGEMENT_PORT:-5672}:5672"
      - "${TCD_RABBITMQ_BROKER_PORT:-15672}:15672"
    volumes:
      - "${TCD_RABBITMQ_BROKER_DATA_PATH:-./dataRabbitMQ}:/var/lib/rabbitmq/mnesia/"


  jee-server-dev:
    build: .
    image: 'tcd-jee-server:dev'
    container_name: 'tcd-jee-server-dev'
    restart: always
    ports:
      - "${TCD_JEE_SERVER_PORT:-8080}:8080"
    environment:
      - DB_AUTHENTICATION_DATABASE=${TCD_MONGO_AUTHENTICATION_DATABASE:-admin}
      - DB_USERNAME=${TCD_MONGO_ROOT_USERNAME:-admin}
      - DB_PASSWORD=${TCD_MONGO_ROOT_PASSWORD:-admin}
      - DB_NAME=${TCD_MONGO_DATABASE_NAME:-database}-dev
      - DB_PORT=${TCD_MONGO_PORT:-27017}
      - DB_HOST=${TCD_MONGO_HOST:-mongo}
      - BROKER_HOST=${TCD_RABBITMQ_BROKER_HOST:-rabbitmq}
      - BROKER_PORT=${TCD_RABBITMQ_BROKER_PORT:-15672}
      - JEE_SECURITY_TOKEN_SECRET=${TCD_JEE_SECURITY_TOKEN_SECRET:-default}

    jee-server-prod:
      build: .
      image: 'tcd-jee-server:prod'
      container_name: 'tcd-jee-server-prod'
      restart: always
      ports:
        - "${TCD_JEE_SERVER_PORT:-8080}:8080"
      environment:
        - DB_AUTHENTICATION_DATABASE=${TCD_MONGO_AUTHENTICATION_DATABASE:-admin}
        - DB_USERNAME=${TCD_MONGO_ROOT_USERNAME:-admin}
        - DB_PASSWORD=${TCD_MONGO_ROOT_PASSWORD:-admin}
        - DB_NAME=${TCD_MONGO_DATABASE_NAME:-database}-prod
        - DB_PORT=${TCD_MONGO_PORT:-27017}
        - DB_HOST=${TCD_MONGO_HOST:-mongo}
        - BROKER_HOST=${TCD_RABBITMQ_BROKER_HOST:-rabbitmq}
        - BROKER_PORT=${TCD_RABBITMQ_BROKER_PORT:-15672}
        - JEE_SECURITY_TOKEN_SECRET=${TCD_JEE_SECURITY_TOKEN_SECRET:-default}
