version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ${TCD_MONGO_DATA_PATH:-./data}:/data/db
    ports:
      - ${TCD_MONGO_PORT:-27017}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-admin}


    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - "${TCD_EXPRESS_PORT:-9001}:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME=${TCD_MONGO_EXPRESS_ADMIN_USERNAME:-admin}
        ME_CONFIG_MONGODB_ADMINPASSWORD=${TCD_MONGO_EXPRESS_ADMIN_PASSWORD:-admin}
        ME_CONFIG_BASICAUTH_USERNAME=${TCD_MONGO_EXPRESS_USER_USERNAME:-user}
        ME_CONFIG_BASICAUTH_PASSWORD=${TCD_MONGO_EXPRESS_USER_PASSWORD:-user}

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    network_mode: 'host'
    ports:
      - "${TCD_RABBITMQ_MANAGEMENT_PORT:-5672}:5672"
      - "${TCD_RABBITMQ_BROKER_PORT:-15672}:15672"
  jee-server:
    build: .
    ports:
    - "${TCD_JEE_SERVER_PORT:-8080}:8080"
    environment:
      - DB_AUTHENTICATION_DATABASE=${TCD_AUTHENTICATION_DATABASE:-admin}
      - DB_USERNAME=${TCD_DB_USERNAME:-admin}
      - DB_PASSWORD=${TCD_DB_PASSWORD:-admin}
      - DB_NAME=${TCD_MONGO_NAME:-database}
      - DB_PORT=${TCD_MONGO_PORT:-27017}
      - DB_HOST=${TCD_MONGO_HOST:-127.0.0.1}
      - BROKER_HOST=${TCD_RABBITMQ_BROKER_HOST:-127.0.0.1}
      - BROKER_PORT=${TCD_RABBITMQ_MANAGEMENT_PORT:-5672}
    restart: always